--creating tables

CREATE TABLE STUDENT(
    USN VARCHAR(10),
    SName VARCHAR(10),
    Address VARCHAR(10),
    Phone NUMBER(10),
    Gender CHAR,
    CONSTRAINT STUDENT_PK PRIMARY KEY (USN)
);

CREATE TABLE SEMSEC(
    SSID VARCHAR(10),
    Sem NUMBER(10),
    Sec CHAR,
    CONSTRAINT TABLE_PK PRIMARY KEY (SSID),
    CONSTRAINT C CHECK (Sem BETWEEN 1 AND 8)
);

CREATE TABLE CLASS(
    USN VARCHAR(10),
    SSID VARCHAR(10),
    CONSTRAINT CLASS_PK PRIMARY KEY(USN,SSID),
    CONSTRAINT CLASS_FK1 FOREIGN KEY (USN) REFERENCES STUDENT(USN) ON DELETE CASCADE,
    CONSTRAINT CLASS_FK2 FOREIGN KEY (SSID) REFERENCES SEMSEC(SSID) ON DELETE CASCADE
);

CREATE TABLE COURSE(
    Subcode VARCHAR(10),
    Title VARCHAR(20),
    Sem NUMBER(1),
    Credits NUMBER(2),
    CONSTRAINT COURSE_C CHECK (Sem BETWEEN 1 AND 8),
    CONSTRAINT COURSE_PK PRIMARY KEY(Subcode)
);

CREATE TABLE IAMARKS(
    USN VARCHAR(10),
    Subcode VARCHAR(10),
    SSID VARCHAR(10),
    Test1 NUMBER(3),
    Test2 NUMBER(3),
    Test3 NUMBER(3),
    FinalIA NUMBER(3),
    CONSTRAINT IAMARKS_PK PRIMARY KEY (USN , SubCode , SSID),
    CONSTRAINT IAMARKS_FK1 FOREIGN KEY (USN )REFERENCES STUDENT(USN),
    CONSTRAINT IAMARKS_FK2 FOREIGN KEY (Subcode) REFERENCES COURSE(Subcode),
    CONSTRAINT IAMARKS_FK3 FOREIGN KEY (SSID) REFERENCES SEMSEC(SSID)
);

--inserting data

INSERT INTO STUDENT VALUES ('&USN','&SName','&Address','&Phone','&Gender');
INSERT INTO SEMSEC VALUES ('&SSID',&Sem,'&Sec');
INSERT INTO CLASS VALUES ('&USN','&SSID');
INSERT INTO COURSE VALUES ('&Subcode','&Title',&Sem,&Credits);
INSERT INTO IAMARKS VALUES ('&USN','&Subcode','&SSID',&Test1,&Test2,&Test3,&FinalIA);

--queries

--1 (set sem and section as mentioned)
SELECT S.USN , S.SName , S.Address
FROM STUDENT S, SEMSEC SS , CLASS C
WHERE S.USN = C.USN AND SS.SSID = C.SSID AND SS.SEM = 5;

--2 

SELECT COUNT(S.Gender) 
FROM STUDENT S , CLASS C , SEMSEC SS
WHERE S.USN = C.USN AND C.SSID = SS.SSID
GROUP BY SS.Sem ,SS.Sec;

--3  (set usn acc to query)

CREATE VIEW S1IA AS
SELECT S.USN , IA.Test1 
FROM STUDENT S , IAMARKS IA
WHERE S.USN = IA.USN  AND S.USN = '1mv18cs001';

SELECT * FROM S1IA;

--4
UPDATE IAMARKS 
SET FinalIA = ((Test1+Test2+Test3) - (CASE
            WHEN Test1<Test2 and Test2<Test3 THEN Test1
            WHEN Test1<Test2 and Test3<Test2 THEN Test2
            ELSE Test3
            END
            ))/2;


--5 (set sem values accordingly)
SELECT S.USN , S.Sname , IA.FinalIA , (CASE
    WHEN IA.FinalIA BETWEEN 17 AND 20 THEN 'Outstanding'
    WHEN IA.FinalIA BETWEEN 12 AND 16 THEN 'Average'
    ELSE 'Weak'
    END
) as CAT 
FROM STUDENT S , IAMARKS IA, CLASS C , SEMSEC SS 
WHERE S.USN = IA.USN AND SS.SSID = IA.SSID AND SS.Sem = 5;